### ISSUE TITLE
[Proposal for improvement] Additional description for setting the Authentication Method of Token Endpoint to POST

### ISSUE THREAD

**Issue by c-yan** [onelogin/onelogin-oidc-node#1]
When I tried the sample of Auth Flow, I just could not make it work.
After numbers of trial and error, I found out that it works properly by changing the Authentication Method of Token Endpoint from Basic to POST in the SSO setting of App.
I think that additional description in "1. Auth Flow/README.md" should be placed about the necessity of this setting.

**Comment by richet** [comment]
Good point. Thanks
