### ISSUE TITLE
wrong id token provider

### ISSUE THREAD

**Issue by cyberf4n** [onelogin/onelogin-oidc-node#12]
Hi

I get this error:

**id token not issued by correct OpenID provider - expected: https://myapp.onelogin.com/oidc | from: https://openid-connect-eu.onelogin.com/oid**

I've definitely changed the issuer:

```
const OIDC_BASE_URI = `https://myapp.onelogin.com/oidc`;

var strategy = new OneLoginStrategy({
  issuer: OIDC_BASE_URI,
```

Not sure what to do...

**Comment by cyberf4n** [comment]
a workaround would be to comment this line in strategy.js:

```
        //if (jwtClaims.iss !== meta.issuer) return self.error(new Error('id token not issued by correct OpenID provider - ' +
          //                                                             'expected: ' + meta.issuer + ' | from: ' + jwtClaims.iss));

```

but it is not a good resolution....

**Comment by richet** [comment]
Where did you find the setting for OIDC_BASE_URI? This seems like old code and is definitely a bug that needs to be fixed if it is still floating around somewhere. 

OIDC_BASE_URI / issuer should never contain the onelogin instance subdomain like **myapp.onelogin.com**. 

It must always be one of the following

US instances: openid-connect.onelogin.com
EU instances: openid-connect-eu.onelogin.com

**Comment by cyberf4n** [comment]
Hi, the OIDC_BASE_URI is the application I've created in OneLogin page. Should this be the one used? Obviously "myapp" is replaced by the actual name of the application. The error does states that the issuer has to be in that format. Example:
MyLoginApplication.onelogin.com/oidc - is this wrong? Should I not user the app link? The ID and secret are from the application, would this be a problem? I do not use the ID and secret from API credentials.
Hope this makes sense, if not let me know and I will paste some examples maybe.
Thanks
