### ISSUE TITLE
onelogin "Halogen Software" App Store needs to be updated

### ISSUE THREAD

**Issue by beniluul** [onelogin/onelogin-oidc-node#16]
As you may be aware, **Halogen Software** has recently been acquired by **Saba Software**.
https://www.saba.com/press/news/saba-software-announces-agreement-to-acquire-halogen-software
Thus, the "Halogen Software" TalentSpace Product is currently called "Saba TalentSpace".
 
Could you update your public documentation:
  https://www.onelogin.com/connector/halogen
  https://www.onelogin.com/connector/halogenadmin
 
It is using the old Saba logo. You can see what Saba Software current logo looks like from the above article or by just visiting saba.com

    You can get the logo from here:
    https://archive.org/download/sabalogo/sabalogo.png

Also, maybe the URLs could be updated (e.g. - https://www.onelogin.com/connector/talentspace) ?
 
  
Secondly, the following are screenshots of your onelogin **App Store** when searching for "Halogen":
  https://archive.org/download/app_store2/app_store2.jpg
  https://archive.org/download/app_store/app_store.jpg
 
We are having to tell our clients to search for "Halogen Software" to implement SSO. It would be great if you could update these to say "Saba TalentSpace" and with the current logo. 
 
For the built-in "Rectangular Icon", you can use:
  https://archive.org/download/sabafulllogo/sabafulllogo.png
 
For the built-in "Square Icon", you can use:
  https://archive.org/download/sabalogo/sabalogo.png
 
 
Lastly, for the "**Configuration**" section of the SAML SSO app you have for Halogen Software, the built-in app appears to only come with a "**SAML Audience URL**" field and a "**SAML Consumer URL**" field which will fail when configuring this with clients.
 
It should come with the "**SAML Consumer URL**", "**SAML Audience URL**", "**SAML Recipient**", and "**ACS URL Validator**".
 
Otherwise, we're forced to walk clients through adding a custom app via "**SAML Test Connector (IdP w/ attr**") which comes with all these fields to get this working successfully.

**Comment by pitbulk** [comment]
Sorry but this place is not the right place to report this kind of issue.

This is an OIDC repository and only issues related to its uses should be registered.

Contact [Onelogin support](https://onelogin.service-now.com/support)
