### ISSUE TITLE
Implicit Flow not working?

### ISSUE THREAD

**Issue by ConnorBrereton** [onelogin/onelogin-oidc-node#17]
I'm going through the tutorial and found a few issues:

1. > Clone this repo and then update /javascripts/main.js with the client_id you obtained from OneLogin and the subdomain of your OneLogin account.

There seems (on my end) to be an issue with the `client_id` and `subdomain` instructions. It's not entirely obvious if the `client_id` needs to be the one that is issued in the OneLogin App or our personal API one given to us. If it's the later, that will throw an error with the following output:

```
error: invalid_client
error_description: client is invalid
state: 7f38287367a6475f9eaa6c0b6370c1c
```

When I have the correct `client_id` setup in the `javascripts/main.js` file I am not seeing anywhere there being a field for me to specify the parameter of `subdomain`. Can someone tell me where this is supposed to be specified as I don't see it being a valid parameter per the codes layout ATM?

2. > You will need to add your callback url to the list of approved Redirect URIs for your OneLogin OIDC app via the Admin portal. e.g. http://localhost:3000/oauth/callback

So I have `http://localhost:3000/oauth/callback` setup in the `configuration --> redirect URI's` field and it still is throwing me an issue:

```
error: redirect_uri_mismatch
error_description: redirect_uri did not match any client's registered redirect_uris
state: 497592e85aae4273ad05f397fbd6dcc9
```

Can I get a hand clarifying what's going wrong? I'd be more than happy to update the docs in return for a hand in this :)

**Comment by ThrownJupiter** [comment]
hi @ConnorBrereton ,
Did you set the variable for 'OIDC_REDIRECT_URI=' in your .env file?

Thanks,
Andrew

**Comment by ConnorBrereton** [comment]
Hi Andrew - when I worked there and configured it, yes. The issue was my token was not allowing me access. Pretty strange. Cheers!
