### ISSUE TITLE
[Question] About scope: email

### ISSUE THREAD

**Issue by c-yan** [onelogin/onelogin-oidc-node#2]
Looking at the following source code, both "email" and "profile" are specified within "scope".
https://github.com/onelogin/onelogin-oidc-node/blob/master/1.%20Auth%20Flow/app.js#L100

However, when I check the OneLogin's OIDC metadata, "email" is not included in "scopes_supported".
It is working without problems, but I wonder if it is appropriate to specify what you do not support within an official sample.

**Comment by richet** [comment]
Nice catch. Thanks
