### ISSUE TITLE
Failed to obtain access token for 1. Auth Flow

### ISSUE THREAD

**Issue by AmazingDevTeam** [onelogin/onelogin-oidc-node#21]
I am trying out this tutorial but encountered the above error can anyone help verify if this tutorial is working?
![error](https://user-images.githubusercontent.com/56999169/122109594-1f229e00-ce50-11eb-80ae-b2f4bad7c382.PNG)

**Comment by richet** [comment]
Typically this is due to access being blocked via VPN or firewall. There have also been some reports of this when using https on localhost with an invalid certificate. Please check all of these things and try again.
