### ISSUE TITLE
iat is in the future 1536067127

### ISSUE THREAD

**Issue by albertStaalburger** [onelogin/onelogin-oidc-node#6]
I cannot seem to get the SPA example working.
Every time I try to authenticate I keep getting the error: 

> iat is in the future 1536067127

Can this be related to a config issue or rather system date & time?

**Comment by richet** [comment]
I've not seen this before so would expect that its related to system time.

**Comment by bey6** [comment]
> I've not seen this before so would expect that its related to system time.

Thanks, It's work for me.  😀

**Comment by cuongtong** [comment]
yeah, got the same error here and set my system time to Set time automatically and it started to work. I had my time set as manually before.
