### ISSUE TITLE
How to implement silent renew with one login ?

### ISSUE THREAD

**Issue by lyxhaven** [onelogin/onelogin-oidc-node#7]
I don't see this example implementing silent renew so I'm wondering how we can do it with one login. I tried to implement it in my react app but I just got this `End User Authentication required` error when I turned on `automaticSilentRenew` (it triggered `signinSilent` from the `oidc-client` lib when the token is about to expire). It seems to me that one login could not recognize the `id_token_hint` in the request param that is sent from the silent renew call by the lib. Thus, it doesn't recognize that the user has an active session with one login while receiving the silent renew request from the client. How can we solve this problem ? Thanks !

**Comment by lyxhaven** [comment]
After OneLogin released their support for silent renew couple days ago. They same code got a different error now: "error while renewing the access token Error: id_token_hint and authenticated subject do not match".

**Comment by lyxhaven** [comment]
I seem to solve the issue by setting `includeIdTokenInSilentRenew` to false to get rid of `id_token_hint` from the silent renew request param.

**Comment by richet** [comment]
Apologies for the slow response in addressing this issue. OneLogin does not currently support the optional `id_token_hint` field so as you have found out the answer here is to exclude it from your request in order to get silent renew working.
